// Opens a print-ready window with the generated Job Description so the user
// can save it as a PDF (via the browser's native "Save as PDF"). Keeps zero
// runtime dependencies — works on all modern browsers, desktop and mobile.

type JdMeta = {
  title: string;
  company?: string;
  city?: string;
  jobType?: string;
  workMode?: string;
  salary?: string;
  html: string;
};

const esc = (s: string) =>
  (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function downloadJdPdf(meta: JdMeta) {
  const chips = [meta.city, meta.jobType, meta.workMode, meta.salary]
    .filter(Boolean)
    .map((c) => `<span class="chip">${esc(String(c))}</span>`)
    .join("");

  const doc = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${esc(meta.title || "Job Description")} · JobsKart</title>
<style>
  *{box-sizing:border-box}
  html,body{margin:0;padding:0;background:#fff;color:#0f172a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
  .page{max-width:780px;margin:0 auto;padding:40px 44px}
  .brand{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #1A55BD;padding-bottom:14px;margin-bottom:22px}
  .brand .logo{font-weight:800;letter-spacing:-.02em;color:#1A55BD;font-size:20px}
  .brand .tag{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.08em}
  h1{font-size:26px;line-height:1.2;margin:0 0 6px;letter-spacing:-.01em}
  .company{color:#475569;font-size:14px;margin-bottom:14px}
  .chips{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:22px}
  .chip{display:inline-block;background:#EEF2FF;color:#1A55BD;border:1px solid #DCE4FA;font-size:12px;font-weight:600;padding:4px 10px;border-radius:999px}
  .jd h4{font-size:14px;text-transform:uppercase;letter-spacing:.06em;color:#0f172a;margin:22px 0 8px}
  .jd p{margin:0 0 10px;font-size:14px;line-height:1.6;color:#1e293b}
  .jd ul{padding-left:20px;margin:0 0 12px}
  .jd li{font-size:14px;line-height:1.55;color:#1e293b;margin-bottom:4px}
  .jd em{color:#475569;font-style:normal;background:#F8FAFC;padding:2px 6px;border-radius:4px}
  .footer{margin-top:36px;padding-top:14px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8;display:flex;justify-content:space-between}
  .cta{margin-top:28px;background:#0F172A;color:#fff;border-radius:12px;padding:18px 20px}
  .cta .t{font-size:13px;font-weight:700;letter-spacing:.02em}
  .cta .s{font-size:12px;color:#cbd5e1;margin-top:4px}
  @media print { .no-print{display:none} .page{padding:24px 28px} @page { size:A4; margin:14mm } }
</style>
</head>
<body>
<div class="page">
  <div class="brand">
    <div class="logo">JobsKart</div>
    <div class="tag">Job Description</div>
  </div>
  <h1>${esc(meta.title || "Untitled role")}</h1>
  ${meta.company ? `<div class="company">${esc(meta.company)}</div>` : ""}
  ${chips ? `<div class="chips">${chips}</div>` : ""}
  <div class="jd">${meta.html || "<p><em>No description generated.</em></p>"}</div>
  <div class="cta">
    <div class="t">Apply on JobsKart</div>
    <div class="s">Scan &amp; apply in 30 seconds — verified employers, no spam.</div>
  </div>
  <div class="footer">
    <span>Generated by JobsKart</span>
    <span>${new Date().toLocaleDateString()}</span>
  </div>
</div>
<div class="no-print" style="position:fixed;top:12px;right:12px;display:flex;gap:8px">
  <button onclick="window.print()" style="background:#1A55BD;color:#fff;border:0;border-radius:8px;padding:10px 14px;font-weight:600;cursor:pointer">Download PDF</button>
  <button onclick="window.close()" style="background:#fff;color:#0f172a;border:1px solid #e2e8f0;border-radius:8px;padding:10px 14px;font-weight:600;cursor:pointer">Close</button>
</div>
<script>window.addEventListener('load',()=>setTimeout(()=>window.print(),350))</script>
</body>
</html>`;

  const w = window.open("", "_blank", "noopener,noreferrer,width=900,height=1000");
  if (!w) {
    // popup blocked — fall back to blob download of the HTML
    const blob = new Blob([doc], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(meta.title || "job-description").replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.html`;
    a.click();
    URL.revokeObjectURL(url);
    return;
  }
  w.document.open();
  w.document.write(doc);
  w.document.close();
}
