/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupEmployerRouteImport } from './routes/signup.employer'
import { Route as SignupCandidateRouteImport } from './routes/signup.candidate'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthenticatedEmployerDashboardRouteImport } from './routes/_authenticated/employer/dashboard'
import { Route as AuthenticatedCandidateSavedRouteImport } from './routes/_authenticated/candidate/saved'
import { Route as AuthenticatedCandidateDashboardRouteImport } from './routes/_authenticated/candidate/dashboard'
import { Route as AuthenticatedCandidateApplicationsRouteImport } from './routes/_authenticated/candidate/applications'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmployerRoute = SignupEmployerRouteImport.update({
  id: '/signup/employer',
  path: '/signup/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCandidateRoute = SignupCandidateRouteImport.update({
  id: '/signup/candidate',
  path: '/signup/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AuthenticatedEmployerDashboardRoute =
  AuthenticatedEmployerDashboardRouteImport.update({
    id: '/employer/dashboard',
    path: '/employer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateSavedRoute =
  AuthenticatedCandidateSavedRouteImport.update({
    id: '/candidate/saved',
    path: '/candidate/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateDashboardRoute =
  AuthenticatedCandidateDashboardRouteImport.update({
    id: '/candidate/dashboard',
    path: '/candidate/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateApplicationsRoute =
  AuthenticatedCandidateApplicationsRouteImport.update({
    id: '/candidate/applications',
    path: '/candidate/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/_authenticated/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/_authenticated/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/_authenticated/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/_authenticated/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/jobs/$jobId'
    | '/signup/candidate'
    | '/signup/employer'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/saved'
    | '/employer/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/jobs/$jobId'
    | '/signup/candidate'
    | '/signup/employer'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/saved'
    | '/employer/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/jobs/$jobId'
    | '/signup/candidate'
    | '/signup/employer'
    | '/_authenticated/candidate/applications'
    | '/_authenticated/candidate/dashboard'
    | '/_authenticated/candidate/saved'
    | '/_authenticated/employer/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupCandidateRoute: typeof SignupCandidateRoute
  SignupEmployerRoute: typeof SignupEmployerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/employer': {
      id: '/signup/employer'
      path: '/signup/employer'
      fullPath: '/signup/employer'
      preLoaderRoute: typeof SignupEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/candidate': {
      id: '/signup/candidate'
      path: '/signup/candidate'
      fullPath: '/signup/candidate'
      preLoaderRoute: typeof SignupCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/_authenticated/employer/dashboard': {
      id: '/_authenticated/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof AuthenticatedEmployerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/saved': {
      id: '/_authenticated/candidate/saved'
      path: '/candidate/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof AuthenticatedCandidateSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/dashboard': {
      id: '/_authenticated/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof AuthenticatedCandidateDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/applications': {
      id: '/_authenticated/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidateApplicationsRoute: typeof AuthenticatedCandidateApplicationsRoute
  AuthenticatedCandidateDashboardRoute: typeof AuthenticatedCandidateDashboardRoute
  AuthenticatedCandidateSavedRoute: typeof AuthenticatedCandidateSavedRoute
  AuthenticatedEmployerDashboardRoute: typeof AuthenticatedEmployerDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidateApplicationsRoute:
    AuthenticatedCandidateApplicationsRoute,
  AuthenticatedCandidateDashboardRoute: AuthenticatedCandidateDashboardRoute,
  AuthenticatedCandidateSavedRoute: AuthenticatedCandidateSavedRoute,
  AuthenticatedEmployerDashboardRoute: AuthenticatedEmployerDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupCandidateRoute: SignupCandidateRoute,
  SignupEmployerRoute: SignupEmployerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
