/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as SignupEmployerRouteImport } from './routes/signup.employer'
import { Route as SignupCandidateRouteImport } from './routes/signup.candidate'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmployerLoginRouteImport } from './routes/employer.login'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedOnboardingCandidateRouteImport } from './routes/_authenticated/onboarding/candidate'
import { Route as AuthenticatedEmployerTeamRouteImport } from './routes/_authenticated/employer/team'
import { Route as AuthenticatedEmployerJobsRouteImport } from './routes/_authenticated/employer/jobs'
import { Route as AuthenticatedEmployerDashboardRouteImport } from './routes/_authenticated/employer/dashboard'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer/company'
import { Route as AuthenticatedCandidateSavedRouteImport } from './routes/_authenticated/candidate/saved'
import { Route as AuthenticatedCandidateProfileRouteImport } from './routes/_authenticated/candidate/profile'
import { Route as AuthenticatedCandidateDashboardRouteImport } from './routes/_authenticated/candidate/dashboard'
import { Route as AuthenticatedCandidateApplicationsRouteImport } from './routes/_authenticated/candidate/applications'
import { Route as AuthenticatedEmployerJobsNewRouteImport } from './routes/_authenticated/employer/jobs.new'
import { Route as AuthenticatedEmployerJobsJobIdApplicantsRouteImport } from './routes/_authenticated/employer/jobs.$jobId.applicants'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmployerRoute = SignupEmployerRouteImport.update({
  id: '/signup/employer',
  path: '/signup/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCandidateRoute = SignupCandidateRouteImport.update({
  id: '/signup/candidate',
  path: '/signup/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerLoginRoute = EmployerLoginRouteImport.update({
  id: '/employer/login',
  path: '/employer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingCandidateRoute =
  AuthenticatedOnboardingCandidateRouteImport.update({
    id: '/onboarding/candidate',
    path: '/onboarding/candidate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerTeamRoute =
  AuthenticatedEmployerTeamRouteImport.update({
    id: '/employer/team',
    path: '/employer/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsRoute =
  AuthenticatedEmployerJobsRouteImport.update({
    id: '/employer/jobs',
    path: '/employer/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerDashboardRoute =
  AuthenticatedEmployerDashboardRouteImport.update({
    id: '/employer/dashboard',
    path: '/employer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/employer/company',
    path: '/employer/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateSavedRoute =
  AuthenticatedCandidateSavedRouteImport.update({
    id: '/candidate/saved',
    path: '/candidate/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateProfileRoute =
  AuthenticatedCandidateProfileRouteImport.update({
    id: '/candidate/profile',
    path: '/candidate/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateDashboardRoute =
  AuthenticatedCandidateDashboardRouteImport.update({
    id: '/candidate/dashboard',
    path: '/candidate/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateApplicationsRoute =
  AuthenticatedCandidateApplicationsRouteImport.update({
    id: '/candidate/applications',
    path: '/candidate/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsNewRoute =
  AuthenticatedEmployerJobsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEmployerJobsRoute,
  } as any)
const AuthenticatedEmployerJobsJobIdApplicantsRoute =
  AuthenticatedEmployerJobsJobIdApplicantsRouteImport.update({
    id: '/$jobId/applicants',
    path: '/$jobId/applicants',
    getParentRoute: () => AuthenticatedEmployerJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/employer/login': typeof EmployerLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/u/$slug': typeof USlugRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRouteWithChildren
  '/employer/team': typeof AuthenticatedEmployerTeamRoute
  '/onboarding/candidate': typeof AuthenticatedOnboardingCandidateRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/employer/jobs/$jobId/applicants': typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/employer/login': typeof EmployerLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/u/$slug': typeof USlugRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRouteWithChildren
  '/employer/team': typeof AuthenticatedEmployerTeamRoute
  '/onboarding/candidate': typeof AuthenticatedOnboardingCandidateRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/employer/jobs/$jobId/applicants': typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/employer/login': typeof EmployerLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/u/$slug': typeof USlugRoute
  '/_authenticated/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/_authenticated/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/_authenticated/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/_authenticated/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/_authenticated/employer/jobs': typeof AuthenticatedEmployerJobsRouteWithChildren
  '/_authenticated/employer/team': typeof AuthenticatedEmployerTeamRoute
  '/_authenticated/onboarding/candidate': typeof AuthenticatedOnboardingCandidateRoute
  '/_authenticated/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/_authenticated/employer/jobs/$jobId/applicants': typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/c/$slug'
    | '/employer/login'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/signup/candidate'
    | '/signup/employer'
    | '/u/$slug'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employer/company'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/team'
    | '/onboarding/candidate'
    | '/employer/jobs/new'
    | '/employer/jobs/$jobId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/c/$slug'
    | '/employer/login'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/signup/candidate'
    | '/signup/employer'
    | '/u/$slug'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employer/company'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/team'
    | '/onboarding/candidate'
    | '/employer/jobs/new'
    | '/employer/jobs/$jobId/applicants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/c/$slug'
    | '/employer/login'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/signup/candidate'
    | '/signup/employer'
    | '/u/$slug'
    | '/_authenticated/candidate/applications'
    | '/_authenticated/candidate/dashboard'
    | '/_authenticated/candidate/profile'
    | '/_authenticated/candidate/saved'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/dashboard'
    | '/_authenticated/employer/jobs'
    | '/_authenticated/employer/team'
    | '/_authenticated/onboarding/candidate'
    | '/_authenticated/employer/jobs/new'
    | '/_authenticated/employer/jobs/$jobId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
  EmployerLoginRoute: typeof EmployerLoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SignupCandidateRoute: typeof SignupCandidateRoute
  SignupEmployerRoute: typeof SignupEmployerRoute
  USlugRoute: typeof USlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/employer': {
      id: '/signup/employer'
      path: '/signup/employer'
      fullPath: '/signup/employer'
      preLoaderRoute: typeof SignupEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/candidate': {
      id: '/signup/candidate'
      path: '/signup/candidate'
      fullPath: '/signup/candidate'
      preLoaderRoute: typeof SignupCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/login': {
      id: '/employer/login'
      path: '/employer/login'
      fullPath: '/employer/login'
      preLoaderRoute: typeof EmployerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/candidate': {
      id: '/_authenticated/onboarding/candidate'
      path: '/onboarding/candidate'
      fullPath: '/onboarding/candidate'
      preLoaderRoute: typeof AuthenticatedOnboardingCandidateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/team': {
      id: '/_authenticated/employer/team'
      path: '/employer/team'
      fullPath: '/employer/team'
      preLoaderRoute: typeof AuthenticatedEmployerTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs': {
      id: '/_authenticated/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AuthenticatedEmployerJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/dashboard': {
      id: '/_authenticated/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof AuthenticatedEmployerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/saved': {
      id: '/_authenticated/candidate/saved'
      path: '/candidate/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof AuthenticatedCandidateSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/profile': {
      id: '/_authenticated/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof AuthenticatedCandidateProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/dashboard': {
      id: '/_authenticated/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof AuthenticatedCandidateDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/applications': {
      id: '/_authenticated/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/new': {
      id: '/_authenticated/employer/jobs/new'
      path: '/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AuthenticatedEmployerJobsNewRouteImport
      parentRoute: typeof AuthenticatedEmployerJobsRoute
    }
    '/_authenticated/employer/jobs/$jobId/applicants': {
      id: '/_authenticated/employer/jobs/$jobId/applicants'
      path: '/$jobId/applicants'
      fullPath: '/employer/jobs/$jobId/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedEmployerJobsRoute
    }
  }
}

interface AuthenticatedEmployerJobsRouteChildren {
  AuthenticatedEmployerJobsNewRoute: typeof AuthenticatedEmployerJobsNewRoute
  AuthenticatedEmployerJobsJobIdApplicantsRoute: typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}

const AuthenticatedEmployerJobsRouteChildren: AuthenticatedEmployerJobsRouteChildren =
  {
    AuthenticatedEmployerJobsNewRoute: AuthenticatedEmployerJobsNewRoute,
    AuthenticatedEmployerJobsJobIdApplicantsRoute:
      AuthenticatedEmployerJobsJobIdApplicantsRoute,
  }

const AuthenticatedEmployerJobsRouteWithChildren =
  AuthenticatedEmployerJobsRoute._addFileChildren(
    AuthenticatedEmployerJobsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidateApplicationsRoute: typeof AuthenticatedCandidateApplicationsRoute
  AuthenticatedCandidateDashboardRoute: typeof AuthenticatedCandidateDashboardRoute
  AuthenticatedCandidateProfileRoute: typeof AuthenticatedCandidateProfileRoute
  AuthenticatedCandidateSavedRoute: typeof AuthenticatedCandidateSavedRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerDashboardRoute: typeof AuthenticatedEmployerDashboardRoute
  AuthenticatedEmployerJobsRoute: typeof AuthenticatedEmployerJobsRouteWithChildren
  AuthenticatedEmployerTeamRoute: typeof AuthenticatedEmployerTeamRoute
  AuthenticatedOnboardingCandidateRoute: typeof AuthenticatedOnboardingCandidateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidateApplicationsRoute:
    AuthenticatedCandidateApplicationsRoute,
  AuthenticatedCandidateDashboardRoute: AuthenticatedCandidateDashboardRoute,
  AuthenticatedCandidateProfileRoute: AuthenticatedCandidateProfileRoute,
  AuthenticatedCandidateSavedRoute: AuthenticatedCandidateSavedRoute,
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerDashboardRoute: AuthenticatedEmployerDashboardRoute,
  AuthenticatedEmployerJobsRoute: AuthenticatedEmployerJobsRouteWithChildren,
  AuthenticatedEmployerTeamRoute: AuthenticatedEmployerTeamRoute,
  AuthenticatedOnboardingCandidateRoute: AuthenticatedOnboardingCandidateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  CSlugRoute: CSlugRoute,
  EmployerLoginRoute: EmployerLoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  SignupCandidateRoute: SignupCandidateRoute,
  SignupEmployerRoute: SignupEmployerRoute,
  USlugRoute: USlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
