/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as CandidateLoginRouteImport } from './routes/candidate.login'
import { Route as EmployerLoginRouteImport } from './routes/employer.login'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as LegalWhatsappExtensionRouteImport } from './routes/legal.whatsapp-extension'
import { Route as SignupCandidateRouteImport } from './routes/signup.candidate'
import { Route as SignupEmployerRouteImport } from './routes/signup.employer'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedAdminCreditsRouteImport } from './routes/_authenticated/admin/credits'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminLearningRouteImport } from './routes/_authenticated/admin/learning'
import { Route as AuthenticatedAdminMastersRouteImport } from './routes/_authenticated/admin/masters'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminResumesRouteImport } from './routes/_authenticated/admin/resumes'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin/verifications'
import { Route as AuthenticatedCandidateAlertsRouteImport } from './routes/_authenticated/candidate/alerts'
import { Route as AuthenticatedCandidateApplicationsRouteImport } from './routes/_authenticated/candidate/applications'
import { Route as AuthenticatedCandidateDashboardRouteImport } from './routes/_authenticated/candidate/dashboard'
import { Route as AuthenticatedCandidateDocumentsRouteImport } from './routes/_authenticated/candidate/documents'
import { Route as AuthenticatedCandidateInterviewsRouteImport } from './routes/_authenticated/candidate/interviews'
import { Route as AuthenticatedCandidateNotificationsRouteImport } from './routes/_authenticated/candidate/notifications'
import { Route as AuthenticatedCandidateProfileRouteImport } from './routes/_authenticated/candidate/profile'
import { Route as AuthenticatedCandidateSavedRouteImport } from './routes/_authenticated/candidate/saved'
import { Route as AuthenticatedCandidateSettingsRouteImport } from './routes/_authenticated/candidate/settings'
import { Route as AuthenticatedEmployerActivityRouteImport } from './routes/_authenticated/employer/activity'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer/company'
import { Route as AuthenticatedEmployerCreditsRouteImport } from './routes/_authenticated/employer/credits'
import { Route as AuthenticatedEmployerDashboardRouteImport } from './routes/_authenticated/employer/dashboard'
import { Route as AuthenticatedEmployerDatabaseRouteImport } from './routes/_authenticated/employer/database'
import { Route as AuthenticatedEmployerInterviewsRouteImport } from './routes/_authenticated/employer/interviews'
import { Route as AuthenticatedEmployerJobsRouteImport } from './routes/_authenticated/employer/jobs'
import { Route as AuthenticatedEmployerReportsRouteImport } from './routes/_authenticated/employer/reports'
import { Route as AuthenticatedEmployerResponsesRouteImport } from './routes/_authenticated/employer/responses'
import { Route as AuthenticatedEmployerTeamRouteImport } from './routes/_authenticated/employer/team'
import { Route as AuthenticatedEmployerVerificationRouteImport } from './routes/_authenticated/employer/verification'
import { Route as AuthenticatedOnboardingCandidateRouteImport } from './routes/_authenticated/onboarding/candidate'
import { Route as AuthenticatedOnboardingEmployerRouteImport } from './routes/_authenticated/onboarding/employer'
import { Route as AuthenticatedEmployerJobsBulkRouteImport } from './routes/_authenticated/employer/jobs.bulk'
import { Route as AuthenticatedEmployerJobsNewRouteImport } from './routes/_authenticated/employer/jobs.new'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as AuthenticatedEmployerJobsJobIdApplicantsRouteImport } from './routes/_authenticated/employer/jobs.$jobId.applicants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateLoginRoute = CandidateLoginRouteImport.update({
  id: '/candidate/login',
  path: '/candidate/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerLoginRoute = EmployerLoginRouteImport.update({
  id: '/employer/login',
  path: '/employer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const LegalWhatsappExtensionRoute = LegalWhatsappExtensionRouteImport.update({
  id: '/legal/whatsapp-extension',
  path: '/legal/whatsapp-extension',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCandidateRoute = SignupCandidateRouteImport.update({
  id: '/signup/candidate',
  path: '/signup/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupEmployerRoute = SignupEmployerRouteImport.update({
  id: '/signup/employer',
  path: '/signup/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreditsRoute =
  AuthenticatedAdminCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLearningRoute =
  AuthenticatedAdminLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMastersRoute =
  AuthenticatedAdminMastersRouteImport.update({
    id: '/masters',
    path: '/masters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminResumesRoute =
  AuthenticatedAdminResumesRouteImport.update({
    id: '/resumes',
    path: '/resumes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCandidateAlertsRoute =
  AuthenticatedCandidateAlertsRouteImport.update({
    id: '/candidate/alerts',
    path: '/candidate/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateApplicationsRoute =
  AuthenticatedCandidateApplicationsRouteImport.update({
    id: '/candidate/applications',
    path: '/candidate/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateDashboardRoute =
  AuthenticatedCandidateDashboardRouteImport.update({
    id: '/candidate/dashboard',
    path: '/candidate/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateDocumentsRoute =
  AuthenticatedCandidateDocumentsRouteImport.update({
    id: '/candidate/documents',
    path: '/candidate/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateInterviewsRoute =
  AuthenticatedCandidateInterviewsRouteImport.update({
    id: '/candidate/interviews',
    path: '/candidate/interviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateNotificationsRoute =
  AuthenticatedCandidateNotificationsRouteImport.update({
    id: '/candidate/notifications',
    path: '/candidate/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateProfileRoute =
  AuthenticatedCandidateProfileRouteImport.update({
    id: '/candidate/profile',
    path: '/candidate/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateSavedRoute =
  AuthenticatedCandidateSavedRouteImport.update({
    id: '/candidate/saved',
    path: '/candidate/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateSettingsRoute =
  AuthenticatedCandidateSettingsRouteImport.update({
    id: '/candidate/settings',
    path: '/candidate/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerActivityRoute =
  AuthenticatedEmployerActivityRouteImport.update({
    id: '/employer/activity',
    path: '/employer/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/employer/company',
    path: '/employer/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCreditsRoute =
  AuthenticatedEmployerCreditsRouteImport.update({
    id: '/employer/credits',
    path: '/employer/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerDashboardRoute =
  AuthenticatedEmployerDashboardRouteImport.update({
    id: '/employer/dashboard',
    path: '/employer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerDatabaseRoute =
  AuthenticatedEmployerDatabaseRouteImport.update({
    id: '/employer/database',
    path: '/employer/database',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerInterviewsRoute =
  AuthenticatedEmployerInterviewsRouteImport.update({
    id: '/employer/interviews',
    path: '/employer/interviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsRoute =
  AuthenticatedEmployerJobsRouteImport.update({
    id: '/employer/jobs',
    path: '/employer/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerReportsRoute =
  AuthenticatedEmployerReportsRouteImport.update({
    id: '/employer/reports',
    path: '/employer/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerResponsesRoute =
  AuthenticatedEmployerResponsesRouteImport.update({
    id: '/employer/responses',
    path: '/employer/responses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerTeamRoute =
  AuthenticatedEmployerTeamRouteImport.update({
    id: '/employer/team',
    path: '/employer/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerVerificationRoute =
  AuthenticatedEmployerVerificationRouteImport.update({
    id: '/employer/verification',
    path: '/employer/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingCandidateRoute =
  AuthenticatedOnboardingCandidateRouteImport.update({
    id: '/onboarding/candidate',
    path: '/onboarding/candidate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingEmployerRoute =
  AuthenticatedOnboardingEmployerRouteImport.update({
    id: '/onboarding/employer',
    path: '/onboarding/employer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsBulkRoute =
  AuthenticatedEmployerJobsBulkRouteImport.update({
    id: '/bulk',
    path: '/bulk',
    getParentRoute: () => AuthenticatedEmployerJobsRoute,
  } as any)
const AuthenticatedEmployerJobsNewRoute =
  AuthenticatedEmployerJobsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEmployerJobsRoute,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEmployerJobsJobIdApplicantsRoute =
  AuthenticatedEmployerJobsJobIdApplicantsRouteImport.update({
    id: '/$jobId/applicants',
    path: '/$jobId/applicants',
    getParentRoute: () => AuthenticatedEmployerJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/c/$slug': typeof CSlugRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/employer/login': typeof EmployerLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/legal/whatsapp-extension': typeof LegalWhatsappExtensionRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/u/$slug': typeof USlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/learning': typeof AuthenticatedAdminLearningRoute
  '/admin/masters': typeof AuthenticatedAdminMastersRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/resumes': typeof AuthenticatedAdminResumesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/candidate/alerts': typeof AuthenticatedCandidateAlertsRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/documents': typeof AuthenticatedCandidateDocumentsRoute
  '/candidate/interviews': typeof AuthenticatedCandidateInterviewsRoute
  '/candidate/notifications': typeof AuthenticatedCandidateNotificationsRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/candidate/settings': typeof AuthenticatedCandidateSettingsRoute
  '/employer/activity': typeof AuthenticatedEmployerActivityRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/credits': typeof AuthenticatedEmployerCreditsRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/database': typeof AuthenticatedEmployerDatabaseRoute
  '/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRouteWithChildren
  '/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/employer/responses': typeof AuthenticatedEmployerResponsesRoute
  '/employer/team': typeof AuthenticatedEmployerTeamRoute
  '/employer/verification': typeof AuthenticatedEmployerVerificationRoute
  '/onboarding/candidate': typeof AuthenticatedOnboardingCandidateRoute
  '/onboarding/employer': typeof AuthenticatedOnboardingEmployerRoute
  '/employer/jobs/bulk': typeof AuthenticatedEmployerJobsBulkRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/employer/jobs/$jobId/applicants': typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/c/$slug': typeof CSlugRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/employer/login': typeof EmployerLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/legal/whatsapp-extension': typeof LegalWhatsappExtensionRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/u/$slug': typeof USlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/learning': typeof AuthenticatedAdminLearningRoute
  '/admin/masters': typeof AuthenticatedAdminMastersRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/resumes': typeof AuthenticatedAdminResumesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/candidate/alerts': typeof AuthenticatedCandidateAlertsRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/documents': typeof AuthenticatedCandidateDocumentsRoute
  '/candidate/interviews': typeof AuthenticatedCandidateInterviewsRoute
  '/candidate/notifications': typeof AuthenticatedCandidateNotificationsRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/candidate/settings': typeof AuthenticatedCandidateSettingsRoute
  '/employer/activity': typeof AuthenticatedEmployerActivityRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/credits': typeof AuthenticatedEmployerCreditsRoute
  '/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/employer/database': typeof AuthenticatedEmployerDatabaseRoute
  '/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRouteWithChildren
  '/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/employer/responses': typeof AuthenticatedEmployerResponsesRoute
  '/employer/team': typeof AuthenticatedEmployerTeamRoute
  '/employer/verification': typeof AuthenticatedEmployerVerificationRoute
  '/onboarding/candidate': typeof AuthenticatedOnboardingCandidateRoute
  '/onboarding/employer': typeof AuthenticatedOnboardingEmployerRoute
  '/employer/jobs/bulk': typeof AuthenticatedEmployerJobsBulkRoute
  '/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/employer/jobs/$jobId/applicants': typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/c/$slug': typeof CSlugRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/employer/login': typeof EmployerLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/legal/whatsapp-extension': typeof LegalWhatsappExtensionRoute
  '/signup/candidate': typeof SignupCandidateRoute
  '/signup/employer': typeof SignupEmployerRoute
  '/u/$slug': typeof USlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/learning': typeof AuthenticatedAdminLearningRoute
  '/_authenticated/admin/masters': typeof AuthenticatedAdminMastersRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/resumes': typeof AuthenticatedAdminResumesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/candidate/alerts': typeof AuthenticatedCandidateAlertsRoute
  '/_authenticated/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/_authenticated/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/_authenticated/candidate/documents': typeof AuthenticatedCandidateDocumentsRoute
  '/_authenticated/candidate/interviews': typeof AuthenticatedCandidateInterviewsRoute
  '/_authenticated/candidate/notifications': typeof AuthenticatedCandidateNotificationsRoute
  '/_authenticated/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/_authenticated/candidate/saved': typeof AuthenticatedCandidateSavedRoute
  '/_authenticated/candidate/settings': typeof AuthenticatedCandidateSettingsRoute
  '/_authenticated/employer/activity': typeof AuthenticatedEmployerActivityRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/credits': typeof AuthenticatedEmployerCreditsRoute
  '/_authenticated/employer/dashboard': typeof AuthenticatedEmployerDashboardRoute
  '/_authenticated/employer/database': typeof AuthenticatedEmployerDatabaseRoute
  '/_authenticated/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/_authenticated/employer/jobs': typeof AuthenticatedEmployerJobsRouteWithChildren
  '/_authenticated/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/_authenticated/employer/responses': typeof AuthenticatedEmployerResponsesRoute
  '/_authenticated/employer/team': typeof AuthenticatedEmployerTeamRoute
  '/_authenticated/employer/verification': typeof AuthenticatedEmployerVerificationRoute
  '/_authenticated/onboarding/candidate': typeof AuthenticatedOnboardingCandidateRoute
  '/_authenticated/onboarding/employer': typeof AuthenticatedOnboardingEmployerRoute
  '/_authenticated/employer/jobs/bulk': typeof AuthenticatedEmployerJobsBulkRoute
  '/_authenticated/employer/jobs/new': typeof AuthenticatedEmployerJobsNewRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/_authenticated/employer/jobs/$jobId/applicants': typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/c/$slug'
    | '/candidate/login'
    | '/employer/login'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/legal/whatsapp-extension'
    | '/signup/candidate'
    | '/signup/employer'
    | '/u/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/banners'
    | '/admin/companies'
    | '/admin/credits'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/learning'
    | '/admin/masters'
    | '/admin/plans'
    | '/admin/resumes'
    | '/admin/users'
    | '/admin/verifications'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/documents'
    | '/candidate/interviews'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/candidate/settings'
    | '/employer/activity'
    | '/employer/company'
    | '/employer/credits'
    | '/employer/dashboard'
    | '/employer/database'
    | '/employer/interviews'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/responses'
    | '/employer/team'
    | '/employer/verification'
    | '/onboarding/candidate'
    | '/onboarding/employer'
    | '/employer/jobs/bulk'
    | '/employer/jobs/new'
    | '/api/public/webhooks/razorpay'
    | '/employer/jobs/$jobId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/c/$slug'
    | '/candidate/login'
    | '/employer/login'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/legal/whatsapp-extension'
    | '/signup/candidate'
    | '/signup/employer'
    | '/u/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/banners'
    | '/admin/companies'
    | '/admin/credits'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/learning'
    | '/admin/masters'
    | '/admin/plans'
    | '/admin/resumes'
    | '/admin/users'
    | '/admin/verifications'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/dashboard'
    | '/candidate/documents'
    | '/candidate/interviews'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/candidate/settings'
    | '/employer/activity'
    | '/employer/company'
    | '/employer/credits'
    | '/employer/dashboard'
    | '/employer/database'
    | '/employer/interviews'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/responses'
    | '/employer/team'
    | '/employer/verification'
    | '/onboarding/candidate'
    | '/onboarding/employer'
    | '/employer/jobs/bulk'
    | '/employer/jobs/new'
    | '/api/public/webhooks/razorpay'
    | '/employer/jobs/$jobId/applicants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/jobs'
    | '/mcp'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/c/$slug'
    | '/candidate/login'
    | '/employer/login'
    | '/invite/$token'
    | '/jobs/$jobId'
    | '/legal/whatsapp-extension'
    | '/signup/candidate'
    | '/signup/employer'
    | '/u/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/credits'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/learning'
    | '/_authenticated/admin/masters'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/resumes'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/candidate/alerts'
    | '/_authenticated/candidate/applications'
    | '/_authenticated/candidate/dashboard'
    | '/_authenticated/candidate/documents'
    | '/_authenticated/candidate/interviews'
    | '/_authenticated/candidate/notifications'
    | '/_authenticated/candidate/profile'
    | '/_authenticated/candidate/saved'
    | '/_authenticated/candidate/settings'
    | '/_authenticated/employer/activity'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/credits'
    | '/_authenticated/employer/dashboard'
    | '/_authenticated/employer/database'
    | '/_authenticated/employer/interviews'
    | '/_authenticated/employer/jobs'
    | '/_authenticated/employer/reports'
    | '/_authenticated/employer/responses'
    | '/_authenticated/employer/team'
    | '/_authenticated/employer/verification'
    | '/_authenticated/onboarding/candidate'
    | '/_authenticated/onboarding/employer'
    | '/_authenticated/employer/jobs/bulk'
    | '/_authenticated/employer/jobs/new'
    | '/api/public/webhooks/razorpay'
    | '/_authenticated/employer/jobs/$jobId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CSlugRoute: typeof CSlugRoute
  CandidateLoginRoute: typeof CandidateLoginRoute
  EmployerLoginRoute: typeof EmployerLoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalWhatsappExtensionRoute: typeof LegalWhatsappExtensionRoute
  SignupCandidateRoute: typeof SignupCandidateRoute
  SignupEmployerRoute: typeof SignupEmployerRoute
  USlugRoute: typeof USlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/login': {
      id: '/candidate/login'
      path: '/candidate/login'
      fullPath: '/candidate/login'
      preLoaderRoute: typeof CandidateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/login': {
      id: '/employer/login'
      path: '/employer/login'
      fullPath: '/employer/login'
      preLoaderRoute: typeof EmployerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/legal/whatsapp-extension': {
      id: '/legal/whatsapp-extension'
      path: '/legal/whatsapp-extension'
      fullPath: '/legal/whatsapp-extension'
      preLoaderRoute: typeof LegalWhatsappExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/candidate': {
      id: '/signup/candidate'
      path: '/signup/candidate'
      fullPath: '/signup/candidate'
      preLoaderRoute: typeof SignupCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/employer': {
      id: '/signup/employer'
      path: '/signup/employer'
      fullPath: '/signup/employer'
      preLoaderRoute: typeof SignupEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credits': {
      id: '/_authenticated/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AuthenticatedAdminCreditsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/learning': {
      id: '/_authenticated/admin/learning'
      path: '/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AuthenticatedAdminLearningRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/masters': {
      id: '/_authenticated/admin/masters'
      path: '/masters'
      fullPath: '/admin/masters'
      preLoaderRoute: typeof AuthenticatedAdminMastersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resumes': {
      id: '/_authenticated/admin/resumes'
      path: '/resumes'
      fullPath: '/admin/resumes'
      preLoaderRoute: typeof AuthenticatedAdminResumesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/candidate/alerts': {
      id: '/_authenticated/candidate/alerts'
      path: '/candidate/alerts'
      fullPath: '/candidate/alerts'
      preLoaderRoute: typeof AuthenticatedCandidateAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/applications': {
      id: '/_authenticated/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/dashboard': {
      id: '/_authenticated/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof AuthenticatedCandidateDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/documents': {
      id: '/_authenticated/candidate/documents'
      path: '/candidate/documents'
      fullPath: '/candidate/documents'
      preLoaderRoute: typeof AuthenticatedCandidateDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/interviews': {
      id: '/_authenticated/candidate/interviews'
      path: '/candidate/interviews'
      fullPath: '/candidate/interviews'
      preLoaderRoute: typeof AuthenticatedCandidateInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/notifications': {
      id: '/_authenticated/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof AuthenticatedCandidateNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/profile': {
      id: '/_authenticated/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof AuthenticatedCandidateProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/saved': {
      id: '/_authenticated/candidate/saved'
      path: '/candidate/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof AuthenticatedCandidateSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/settings': {
      id: '/_authenticated/candidate/settings'
      path: '/candidate/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof AuthenticatedCandidateSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/activity': {
      id: '/_authenticated/employer/activity'
      path: '/employer/activity'
      fullPath: '/employer/activity'
      preLoaderRoute: typeof AuthenticatedEmployerActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/credits': {
      id: '/_authenticated/employer/credits'
      path: '/employer/credits'
      fullPath: '/employer/credits'
      preLoaderRoute: typeof AuthenticatedEmployerCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/dashboard': {
      id: '/_authenticated/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof AuthenticatedEmployerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/database': {
      id: '/_authenticated/employer/database'
      path: '/employer/database'
      fullPath: '/employer/database'
      preLoaderRoute: typeof AuthenticatedEmployerDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/interviews': {
      id: '/_authenticated/employer/interviews'
      path: '/employer/interviews'
      fullPath: '/employer/interviews'
      preLoaderRoute: typeof AuthenticatedEmployerInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs': {
      id: '/_authenticated/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AuthenticatedEmployerJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/reports': {
      id: '/_authenticated/employer/reports'
      path: '/employer/reports'
      fullPath: '/employer/reports'
      preLoaderRoute: typeof AuthenticatedEmployerReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/responses': {
      id: '/_authenticated/employer/responses'
      path: '/employer/responses'
      fullPath: '/employer/responses'
      preLoaderRoute: typeof AuthenticatedEmployerResponsesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/team': {
      id: '/_authenticated/employer/team'
      path: '/employer/team'
      fullPath: '/employer/team'
      preLoaderRoute: typeof AuthenticatedEmployerTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/verification': {
      id: '/_authenticated/employer/verification'
      path: '/employer/verification'
      fullPath: '/employer/verification'
      preLoaderRoute: typeof AuthenticatedEmployerVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/candidate': {
      id: '/_authenticated/onboarding/candidate'
      path: '/onboarding/candidate'
      fullPath: '/onboarding/candidate'
      preLoaderRoute: typeof AuthenticatedOnboardingCandidateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/employer': {
      id: '/_authenticated/onboarding/employer'
      path: '/onboarding/employer'
      fullPath: '/onboarding/employer'
      preLoaderRoute: typeof AuthenticatedOnboardingEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs/bulk': {
      id: '/_authenticated/employer/jobs/bulk'
      path: '/bulk'
      fullPath: '/employer/jobs/bulk'
      preLoaderRoute: typeof AuthenticatedEmployerJobsBulkRouteImport
      parentRoute: typeof AuthenticatedEmployerJobsRoute
    }
    '/_authenticated/employer/jobs/new': {
      id: '/_authenticated/employer/jobs/new'
      path: '/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AuthenticatedEmployerJobsNewRouteImport
      parentRoute: typeof AuthenticatedEmployerJobsRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/employer/jobs/$jobId/applicants': {
      id: '/_authenticated/employer/jobs/$jobId/applicants'
      path: '/$jobId/applicants'
      fullPath: '/employer/jobs/$jobId/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedEmployerJobsRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminCreditsRoute: typeof AuthenticatedAdminCreditsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminLearningRoute: typeof AuthenticatedAdminLearningRoute
  AuthenticatedAdminMastersRoute: typeof AuthenticatedAdminMastersRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminResumesRoute: typeof AuthenticatedAdminResumesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
    AuthenticatedAdminCreditsRoute: AuthenticatedAdminCreditsRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
    AuthenticatedAdminLearningRoute: AuthenticatedAdminLearningRoute,
    AuthenticatedAdminMastersRoute: AuthenticatedAdminMastersRoute,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
    AuthenticatedAdminResumesRoute: AuthenticatedAdminResumesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEmployerJobsRouteChildren {
  AuthenticatedEmployerJobsBulkRoute: typeof AuthenticatedEmployerJobsBulkRoute
  AuthenticatedEmployerJobsNewRoute: typeof AuthenticatedEmployerJobsNewRoute
  AuthenticatedEmployerJobsJobIdApplicantsRoute: typeof AuthenticatedEmployerJobsJobIdApplicantsRoute
}

const AuthenticatedEmployerJobsRouteChildren: AuthenticatedEmployerJobsRouteChildren =
  {
    AuthenticatedEmployerJobsBulkRoute: AuthenticatedEmployerJobsBulkRoute,
    AuthenticatedEmployerJobsNewRoute: AuthenticatedEmployerJobsNewRoute,
    AuthenticatedEmployerJobsJobIdApplicantsRoute:
      AuthenticatedEmployerJobsJobIdApplicantsRoute,
  }

const AuthenticatedEmployerJobsRouteWithChildren =
  AuthenticatedEmployerJobsRoute._addFileChildren(
    AuthenticatedEmployerJobsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCandidateAlertsRoute: typeof AuthenticatedCandidateAlertsRoute
  AuthenticatedCandidateApplicationsRoute: typeof AuthenticatedCandidateApplicationsRoute
  AuthenticatedCandidateDashboardRoute: typeof AuthenticatedCandidateDashboardRoute
  AuthenticatedCandidateDocumentsRoute: typeof AuthenticatedCandidateDocumentsRoute
  AuthenticatedCandidateInterviewsRoute: typeof AuthenticatedCandidateInterviewsRoute
  AuthenticatedCandidateNotificationsRoute: typeof AuthenticatedCandidateNotificationsRoute
  AuthenticatedCandidateProfileRoute: typeof AuthenticatedCandidateProfileRoute
  AuthenticatedCandidateSavedRoute: typeof AuthenticatedCandidateSavedRoute
  AuthenticatedCandidateSettingsRoute: typeof AuthenticatedCandidateSettingsRoute
  AuthenticatedEmployerActivityRoute: typeof AuthenticatedEmployerActivityRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerCreditsRoute: typeof AuthenticatedEmployerCreditsRoute
  AuthenticatedEmployerDashboardRoute: typeof AuthenticatedEmployerDashboardRoute
  AuthenticatedEmployerDatabaseRoute: typeof AuthenticatedEmployerDatabaseRoute
  AuthenticatedEmployerInterviewsRoute: typeof AuthenticatedEmployerInterviewsRoute
  AuthenticatedEmployerJobsRoute: typeof AuthenticatedEmployerJobsRouteWithChildren
  AuthenticatedEmployerReportsRoute: typeof AuthenticatedEmployerReportsRoute
  AuthenticatedEmployerResponsesRoute: typeof AuthenticatedEmployerResponsesRoute
  AuthenticatedEmployerTeamRoute: typeof AuthenticatedEmployerTeamRoute
  AuthenticatedEmployerVerificationRoute: typeof AuthenticatedEmployerVerificationRoute
  AuthenticatedOnboardingCandidateRoute: typeof AuthenticatedOnboardingCandidateRoute
  AuthenticatedOnboardingEmployerRoute: typeof AuthenticatedOnboardingEmployerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCandidateAlertsRoute: AuthenticatedCandidateAlertsRoute,
  AuthenticatedCandidateApplicationsRoute:
    AuthenticatedCandidateApplicationsRoute,
  AuthenticatedCandidateDashboardRoute: AuthenticatedCandidateDashboardRoute,
  AuthenticatedCandidateDocumentsRoute: AuthenticatedCandidateDocumentsRoute,
  AuthenticatedCandidateInterviewsRoute: AuthenticatedCandidateInterviewsRoute,
  AuthenticatedCandidateNotificationsRoute:
    AuthenticatedCandidateNotificationsRoute,
  AuthenticatedCandidateProfileRoute: AuthenticatedCandidateProfileRoute,
  AuthenticatedCandidateSavedRoute: AuthenticatedCandidateSavedRoute,
  AuthenticatedCandidateSettingsRoute: AuthenticatedCandidateSettingsRoute,
  AuthenticatedEmployerActivityRoute: AuthenticatedEmployerActivityRoute,
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerCreditsRoute: AuthenticatedEmployerCreditsRoute,
  AuthenticatedEmployerDashboardRoute: AuthenticatedEmployerDashboardRoute,
  AuthenticatedEmployerDatabaseRoute: AuthenticatedEmployerDatabaseRoute,
  AuthenticatedEmployerInterviewsRoute: AuthenticatedEmployerInterviewsRoute,
  AuthenticatedEmployerJobsRoute: AuthenticatedEmployerJobsRouteWithChildren,
  AuthenticatedEmployerReportsRoute: AuthenticatedEmployerReportsRoute,
  AuthenticatedEmployerResponsesRoute: AuthenticatedEmployerResponsesRoute,
  AuthenticatedEmployerTeamRoute: AuthenticatedEmployerTeamRoute,
  AuthenticatedEmployerVerificationRoute:
    AuthenticatedEmployerVerificationRoute,
  AuthenticatedOnboardingCandidateRoute: AuthenticatedOnboardingCandidateRoute,
  AuthenticatedOnboardingEmployerRoute: AuthenticatedOnboardingEmployerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  CSlugRoute: CSlugRoute,
  CandidateLoginRoute: CandidateLoginRoute,
  EmployerLoginRoute: EmployerLoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalWhatsappExtensionRoute: LegalWhatsappExtensionRoute,
  SignupCandidateRoute: SignupCandidateRoute,
  SignupEmployerRoute: SignupEmployerRoute,
  USlugRoute: USlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
