-- Replace the seeded job-title list with the client's Data JD sheet (300 roles).
-- Custom titles added by users (is_custom = true) are kept untouched.
-- Seeded titles not in the new sheet are removed. No other table references
-- job_titles_master by foreign key; salary matching uses title text, so it
-- keeps working against the refreshed list.

DELETE FROM public.job_titles_master WHERE is_custom = false;

INSERT INTO public.job_titles_master (title, is_custom, is_active) VALUES
  ('Account / Relationship Management - Voice / Blended', false, true),
  ('Accounting Assistant', false, true),
  ('Accounts Payable', false, true),
  ('Accounts and Finance Executive', false, true),
  ('Administrative Clerk', false, true),
  ('Advocate', false, true),
  ('Allied Health Manager', false, true),
  ('Aptitude Educator', false, true),
  ('Architect', false, true),
  ('Asset Operations Director', false, true),
  ('Asset Operations Lead', false, true),
  ('Assistant Business Manager', false, true),
  ('Assistant Department Manager', false, true),
  ('Assistant Inspector', false, true),
  ('Assistant Manager Finance', false, true),
  ('Assistant Merchandiser', false, true),
  ('Assistant Store Keeper', false, true),
  ('Assistant Surveyor', false, true),
  ('Assistant System Engineer', false, true),
  ('Assistant Video Editor', false, true),
  ('Associate Coordinator', false, true),
  ('Associate Director', false, true),
  ('Audit Assistant', false, true),
  ('Audit Officer', false, true),
  ('Automotive Service Advisor', false, true),
  ('Ayurvedic Consultant', false, true),
  ('Bakery Helper', false, true),
  ('Banker', false, true),
  ('Beauty Consultant', false, true),
  ('Bilingual/Multilingual Support - Voice / Blended', false, true),
  ('Billing Specialist', false, true),
  ('Biomedical Technician', false, true),
  ('Branch Executive', false, true),
  ('Branch Manager', false, true),
  ('Branch Relations Officer', false, true),
  ('Brand Manager', false, true),
  ('Business Development & Sales Executive', false, true),
  ('Business Development Consultant', false, true),
  ('Business Development Officer', false, true),
  ('Business Development Specialist', false, true),
  ('Business Owner', false, true),
  ('Cabin Crew', false, true),
  ('Call Centre BPO Executive', false, true),
  ('Car Cleaner', false, true),
  ('Car Loan Sales Executive', false, true),
  ('Car Wash Attendant', false, true),
  ('Carpenter Foreman', false, true),
  ('Cashier Lead', false, true),
  ('Cashier Supervisor', false, true),
  ('Catalog Manager', false, true),
  ('Category Lead', false, true),
  ('Category officer', false, true),
  ('Catering Service Manager', false, true),
  ('Channel Development Executive', false, true),
  ('Channel Management Executive', false, true),
  ('Chauffeur', false, true),
  ('Chemistry Instructor', false, true),
  ('Client Advisor', false, true),
  ('Client Relationship Officer', false, true),
  ('Cloud Engineer', false, true),
  ('Collection Officer', false, true),
  ('Collections Executive', false, true),
  ('College Teacher', false, true),
  ('Commis Chef', false, true),
  ('Computer Operator', false, true),
  ('Consultant', false, true),
  ('Content Reviewer', false, true),
  ('Content Writing Intern', false, true),
  ('Corporate Event Coordinator', false, true),
  ('Credit Manager', false, true),
  ('Customer Retention Executive - Voice / Blended', false, true),
  ('Customer Sales Representative', false, true),
  ('Customer Service Supervisor', false, true),
  ('Customer Support Leader', false, true),
  ('Database Developer', false, true),
  ('Debt Collector', false, true),
  ('Delivery Driver', false, true),
  ('Delivery Executive', false, true),
  ('Deputy Supervisor', false, true),
  ('Desktop Publishing Operator', false, true),
  ('Desktop Support Executive', false, true),
  ('Digital Marketer', false, true),
  ('Digital Marketing Consultant', false, true),
  ('Digital Marketing Specialist', false, true),
  ('Digital Marketing Strategist', false, true),
  ('Direct Sales Representative', false, true),
  ('Dish Washer', false, true),
  ('Distributor', false, true),
  ('Documentation Executive', false, true),
  ('Door Supervisor', false, true),
  ('Dot Net Developer', false, true),
  ('Ecommerce Catalog Manager', false, true),
  ('Educator', false, true),
  ('Electrical Maintenance Supervisor', false, true),
  ('Electronic Service Engineer', false, true),
  ('Email Support Executive', false, true),
  ('Embedded Software Developer', false, true),
  ('Emergency Room Nurse', false, true),
  ('Enterprise Sales Manager', false, true),
  ('Equipment Coordinator', false, true),
  ('Event Manager', false, true),
  ('Executive', false, true),
  ('Executive HR', false, true),
  ('Executive Secretary', false, true),
  ('Executive Support Specialist', false, true),
  ('Export Assistant', false, true),
  ('Export Operations Manager', false, true),
  ('External Auditor', false, true),
  ('Fabrication Fitter', false, true),
  ('Facilitator', false, true),
  ('Factory Manager', false, true),
  ('Factory Worker', false, true),
  ('Fashion Assistant', false, true),
  ('Fast Food Cook', false, true),
  ('Fiber Field Engineer', false, true),
  ('Finance Officer', false, true),
  ('Finance Specialist', false, true),
  ('Fitter', false, true),
  ('Floor / Building Manager', false, true),
  ('Food And Beverage Assistant', false, true),
  ('Food Technologist', false, true),
  ('Forklift Operator', false, true),
  ('Franchise Relationship Manager', false, true),
  ('Freelance Photographer', false, true),
  ('Freelance Writer', false, true),
  ('Front Desk Receptionist', false, true),
  ('Front End Architect', false, true),
  ('Front Office Manager', false, true),
  ('Frontend Web Developer', false, true),
  ('Gardener Supervisor', false, true),
  ('Gold Loan Executive', false, true),
  ('Gold Loan Manager', false, true),
  ('HR Associate', false, true),
  ('HR Manager', false, true),
  ('HVAC Engineer', false, true),
  ('Hardware & Network Engineer', false, true),
  ('Head - Customer Success', false, true),
  ('Head - HR', false, true),
  ('Head - Marketing', false, true),
  ('Head Waiter', false, true),
  ('Healthcare Services Manager', false, true),
  ('Healthcare Transcriptionist', false, true),
  ('Heavy Truck Driver', false, true),
  ('Home Loan Executive', false, true),
  ('Home Tutor', false, true),
  ('Hospitality General Manager', false, true),
  ('Hospitality Manager', false, true),
  ('Host / Hostess', false, true),
  ('Hostess', false, true),
  ('Housekeeping Staff', false, true),
  ('Hub Manager', false, true),
  ('Human Resource Administrator', false, true),
  ('Human Resource Manager', false, true),
  ('Human Resources Executive', false, true),
  ('IT Specialist', false, true),
  ('IT Support Specialist', false, true),
  ('Import Export Executive', false, true),
  ('Inside Sales Representative', false, true),
  ('Insurance Manager', false, true),
  ('Insurance Operations Executive', false, true),
  ('Internship Trainee', false, true),
  ('Inventory Executive', false, true),
  ('Inventory Manager', false, true),
  ('Java Developer', false, true),
  ('Jewellery Designer', false, true),
  ('Junior Designer', false, true),
  ('Junior Hr Executive', false, true),
  ('Junior Process Associate', false, true),
  ('Junior Recruiter', false, true),
  ('Kindergarten Teacher', false, true),
  ('Kitchen Manager', false, true),
  ('Laboratory Technician', false, true),
  ('Laptop Repair Technician', false, true),
  ('Lead Generation Specialist', false, true),
  ('Lead Mentor', false, true),
  ('Lead Recruiter', false, true),
  ('Legal Advisor', false, true),
  ('Legal Intern', false, true),
  ('Loader And Unloader', false, true),
  ('Logistics Packing Supervisor', false, true),
  ('Management Operations Intern', false, true),
  ('Market Research Executive', false, true),
  ('Marketing Lead', false, true),
  ('Massage Therapist', false, true),
  ('Mechanical Designer', false, true),
  ('Medical Biller', false, true),
  ('Medical Record / Health Informatics Executive', false, true),
  ('Mobile Technician', false, true),
  ('Molding Process Operator', false, true),
  ('Montessori Teacher', false, true),
  ('Nail Designer', false, true),
  ('Office Admin', false, true),
  ('Office Attendant', false, true),
  ('Online Sales Manager', false, true),
  ('Operation Manager', false, true),
  ('Operations Officer', false, true),
  ('Oracle Database Programmer', false, true),
  ('Packing Boy', false, true),
  ('Patient Care', false, true),
  ('Payroll Executive', false, true),
  ('Pest Control Inspector', false, true),
  ('Pest Control Service Supervisor', false, true),
  ('Pharmacy Technician', false, true),
  ('Photographer', false, true),
  ('Physics Facilitator', false, true),
  ('Pre Sales Advisor', false, true),
  ('Pre Sales Analyst', false, true),
  ('Pre-Primary Teacher', false, true),
  ('Printing Operator', false, true),
  ('Process Manager', false, true),
  ('Production / Manufacturing Head', false, true),
  ('Production Tailor', false, true),
  ('Professor', false, true),
  ('Purchase Assistant', false, true),
  ('Python Developer', false, true),
  ('QA Lead', false, true),
  ('Quality Assurance Associate', false, true),
  ('Quality Auditor', false, true),
  ('Quality Manager', false, true),
  ('RO Equipment Technician', false, true),
  ('RO Technician', false, true),
  ('React Developer', false, true),
  ('Recruitment Associate', false, true),
  ('Regional Manager', false, true),
  ('Regional Sales Manager (B2C)', false, true),
  ('Repair Engineer', false, true),
  ('Research Associate', false, true),
  ('Research Consultant', false, true),
  ('Reservation Manager', false, true),
  ('Reservation Specialist', false, true),
  ('Restaurant Captain', false, true),
  ('Retail Sales Agent', false, true),
  ('Retail Store Auditor', false, true),
  ('Revenue Analyst', false, true),
  ('SIM Card Sales Coordinator', false, true),
  ('SQL Developer', false, true),
  ('Safety Officer', false, true),
  ('Sales Executive', false, true),
  ('Sales Intern', false, true),
  ('Sales Trainee', false, true),
  ('Sales and Marketing Executive', false, true),
  ('Sales and Marketing Leader', false, true),
  ('Salesforce Engineer', false, true),
  ('Scheduling Assistant', false, true),
  ('Science Coach', false, true),
  ('Security Supervisor', false, true),
  ('Senior Associate HR', false, true),
  ('Senior Business Development Executive', false, true),
  ('Senior Civil Engineer', false, true),
  ('Senior Customer Relationship Officer', false, true),
  ('Senior Designer', false, true),
  ('Senior Document Processing Officer', false, true),
  ('Senior E-Commerce Executive', false, true),
  ('Senior Electrician', false, true),
  ('Senior Field Sales Executive', false, true),
  ('Senior Financial Associate', false, true),
  ('Senior Full Stack Developer', false, true),
  ('Senior Human Resource Executive', false, true),
  ('Senior Process Associate', false, true),
  ('Senior Product Specialist', false, true),
  ('Senior Staff Nurse', false, true),
  ('Senior Systems Engineer', false, true),
  ('Senior Teacher', false, true),
  ('Servant', false, true),
  ('Shop Helper', false, true),
  ('Showroom Sales Associate', false, true),
  ('Social Media Intern', false, true),
  ('Software Developer Intern', false, true),
  ('Software Development Engineer Intern', false, true),
  ('Software Engineer Intern', false, true),
  ('Solar Technician', false, true),
  ('Spoken English Trainer', false, true),
  ('Sports / PT Teacher', false, true),
  ('Sports Massage Specialist', false, true),
  ('Store Manager', false, true),
  ('Student Counsellor', false, true),
  ('Systems Administrator Assistant', false, true),
  ('Tailor', false, true),
  ('Tandoor Cook', false, true),
  ('Teacher Intern', false, true),
  ('Teaching Faculty', false, true),
  ('Technical Assistant', false, true),
  ('Technical Support Executive - Non Voice', false, true),
  ('Telecalling Executive', false, true),
  ('Telemarketing Manager', false, true),
  ('Territory Sales Executive', false, true),
  ('Territory Sales Manager', false, true),
  ('Test Supervisor', false, true),
  ('Training and Development Manager', false, true),
  ('Transportation Supervisor', false, true),
  ('Travel Desk Manager', false, true),
  ('Truck Driver', false, true),
  ('Video Security Technician', false, true),
  ('Ward Secretary', false, true),
  ('Welder / Fitter', false, true),
  ('Wholesale Sales Executive', false, true),
  ('Yoga Instructor', false, true),
  ('Zonal Sales Manager (B2C)', false, true),
  ('fund raiser', false, true),
  ('senior processing officer', false, true)
ON CONFLICT (title) DO UPDATE SET is_custom = false, is_active = true;
